#去申请 https://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login
wx:
  config:
    appId: "fadadadasda"
    appSecret: ""
    #模板Id
    templateId: ""
    openidList:
      - ""
#      - ""

message:
  config:
    birthday1: "11-20" #生日日期
    birthday2: "08-31"
    togetherDate: "2021-04-23" #填你们在一起的那天日期
    message: "Have a happy day and love you"

#去申请 https://tianqiapi.com/user/login
weather:
  config:
    appid: ""
    appSecret: ""
    city: "广州"
#注册并购买第二档次，有券，直接白嫖 https://www.apispace.com/eolink/api/myjj/introduction
ApiSpace:
  enableDaily: true #【新增功能】  true：开启每日一句，false：则不开启
  token: ""

server:
  port: 8081

